bacula-db-data:
  image: brunswickheads/bacula-db-data-s390x:latest
  container_name: bacula-db-data

bacula-db:
  image: brunswickheads/bacula-db:7.2.0
  container_name: bacula-db
  hostname: bacula-db
  volumes_from:
    - bacula-db-data:rw
  environment:
    POSTGRES_PASSWORD: U8azIbKXY9QD

bacula-dir:
  image: brunswickheads/bacula-dir-s390x:latest
  container_name: bacula-dir
  hostname: bacula-dir
  ports:
    - "9101:9101" # bconsole -> dir
    - "9102:9102" # dir -> fd
  extra_hosts:
    - "bacula-fd:127.0.0.1"
  volumes:
    - ./configs/ssl:/etc/bacula/ssl:ro
    - ./configs/dir:/etc/bacula:ro
  environment:
    DB_NAME: bacula
    DB_HOST: bacula-db
    DB_USER: postgres
    DB_PASSWORD: U8azIbKXY9QD

bacula-sd:
  image: brunswickheads/bacula-sd-s390x:latest
  container_name: bacula-sd
  hostname: bacula-sd
  ports:
    - "9103:9103" # dir/fd -> sd
  volumes:
    - ./configs/sd:/etc/bacula:ro
    - ./configs/ssl:/etc/bacula/ssl:ro
    - ./backups:/b:rw

bacula-fd:
  image: brunswickheads/bacula-fd-s390x:latest
  container_name: bacula-fd
  hostname: bacula-fd
  ports:
    - "9104:9102" # fd -> sd
  volumes:
    - /:/mnt:ro
  environment:
    FD_PASSWORD: Uu7ooy5Aequiev9caexe2IengaiTh0Ieiegh7Theweqr
